# Generated by Django 4.2.7 on 2023-11-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelsName',
            fields=[
                ('id_name', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'level_name',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='gamer')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('name_level', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='game_api.levelsname', verbose_name='name_level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.users')),
            ],
            options={
                'verbose_name_plural': 'level',
            },
        ),
    ]
